# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    
    unity_export(build_target: "iOS", new_version_code: "increment")
    unity_commit_version_bump

    UI.important("Note that the actual archiving will succeed! '** ARCHIVE SUCCEEDED **' The whole build will fail, because this app does not exist in your AppStore Connect. This will not happen with your actual app, as it will exist in your AppStore Connect.")
    if UI.confirm("Proceed?")
      build_app(scheme: "Unity-iPhone", project: "unity-export/Unity-iPhone.xcodeproj")
    end

    # TODO next step: upload to AppStore Connect
  end
end
