# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"

  lane :custom_lane do
    unity_export(build_target: "Android", new_version_code: "increment")
    unity_commit_version_bump

    if FastlaneCore::Helper.is_mac?
      sh "chmod +x ../unity-export/gradlew" # making sure that we have the permission to execute gradle
    elsif FastlaneCore::Helper.is_windows?
      # nothing to do here
    elsif FastlaneCore::Helper.linux?
      # TODO same as Mac?
    end 

    gradle(
      project_dir: "unity-export",
      task: "assemble",
      build_type: "Release"
    )

    UI.important("Find the APK at '#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}'")

    # TODO next step: upload to PlayStore

  end

  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
