# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"

  lane :custom_lane do
    unity_export(build_target: "Android", new_version_code: "increment")
    #unity_commit_version_bump

    # note that no separate gradle build via fastlane is necessary as an aab was already created via Unity

    # in case we have multiple aabs of different versions and version codes, we just take the one that was last created
    aabs = Dir.glob("../unity-export/*.aab")
    aab = aabs.sort_by { |f| File.ctime(f) }.last

    UI.message("Found aab: '#{aab}'")

    # TODO next step: upload to PlayStore
    #upload_to_play_store(aab: aab)

  end

  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
